import { useState, useEffect, useCallback, useRef } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Search, Download, Calendar, Filter, FileSpreadsheet, FileText, Camera, Loader2, Eye, MapPin, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { MapContainer, TileLayer, CircleMarker, Popup, Polyline, useMap } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import api, { getAssetUrl } from "../lib/api";
import { useToast, Toast } from "../components/Toast";
import { useDebounce } from "../hooks/useDebounce";
import { Pagination } from "../components/Pagination";

type AttendanceStatus =
  | "HADIR"
  | "TERLAMBAT"
  | "ALPHA"
  | "CUTI"
  | "SAKIT"
  | "SETENGAH_HARI"
  | "IZIN_CUTI"
  | "IZIN_SAKIT"
  | "IZIN_SETENGAH_HARI";

interface AttendanceRecord {
  id: string;
  date: string;
  employee?: { id: string; nik: string; name: string; branch?: { id: string; name: string } };
  branch?: { id: string; name: string };
  checkInTime?: string | null;
  checkOutTime?: string | null;
  durationMinutes?: number | null;
  status: AttendanceStatus;
  points: number;
  checkInPhoto?: string | null;
  checkInLat?: number | null;
  checkInLng?: number | null;
  checkOutLat?: number | null;
  checkOutLng?: number | null;
  checkInInsideRadius?: boolean;
  isAutoGenerated?: boolean;
}

interface AttendanceLocationPoint {
  key: string;
  label: string;
  timeLabel: string;
  position: [number, number];
  color: string;
}

function formatTime(iso?: string | null): string {
  if (!iso) return "--:--";
  try {
    return new Date(iso).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit", hour12: false });
  } catch {
    return "--:--";
  }
}

function formatDate(iso?: string): string {
  if (!iso) return "-";
  try {
    return new Date(iso).toLocaleDateString("id-ID", { day: "numeric", month: "short", year: "numeric" });
  } catch {
    return iso;
  }
}

function formatDuration(minutes?: number | null): string {
  if (minutes == null) return "-";
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h}j ${m}m`;
}

function formatCoordinate(value?: number | null): string {
  if (value == null || Number.isNaN(value)) return "-";
  return value.toFixed(6);
}

function toCoordinatePair(lat?: number | null, lng?: number | null): [number, number] | null {
  if (lat == null || lng == null || Number.isNaN(lat) || Number.isNaN(lng)) return null;
  return [lat, lng];
}

const STATUS_LABEL: Record<string, string> = {
  HADIR: "Hadir",
  TERLAMBAT: "Terlambat",
  ALPHA: "Alpha",
  CUTI: "Izin Cuti",
  SAKIT: "Izin Sakit",
  SETENGAH_HARI: "Setengah Hari",
  IZIN_CUTI: "Izin Cuti",
  IZIN_SAKIT: "Izin Sakit",
  IZIN_SETENGAH_HARI: "Setengah Hari",
};

function getStatusBadge(status: string): string {
  switch (status) {
    case "HADIR":
      return "bg-green-50 text-green-700 border-green-200";
    case "TERLAMBAT":
      return "bg-amber-50 text-amber-700 border-amber-200";
    case "CUTI":
    case "IZIN_CUTI":
      return "bg-blue-50 text-blue-700 border-blue-200";
    case "SAKIT":
    case "IZIN_SAKIT":
      return "bg-purple-50 text-purple-700 border-purple-200";
    case "SETENGAH_HARI":
    case "IZIN_SETENGAH_HARI":
      return "bg-indigo-50 text-indigo-700 border-indigo-200";
    case "ALPHA":
      return "bg-red-50 text-red-700 border-red-200";
    default:
      return "bg-gray-50 text-gray-700 border-gray-200";
  }
}

function buildLocationPoints(record: AttendanceRecord): AttendanceLocationPoint[] {
  const points: AttendanceLocationPoint[] = [];
  const checkInPosition = toCoordinatePair(record.checkInLat, record.checkInLng);
  const checkOutPosition = toCoordinatePair(record.checkOutLat, record.checkOutLng);

  if (checkInPosition) {
    points.push({
      key: "check-in",
      label: "Titik Masuk",
      timeLabel: formatTime(record.checkInTime),
      position: checkInPosition,
      color: "#059669",
    });
  }

  if (checkOutPosition) {
    points.push({
      key: "check-out",
      label: "Titik Keluar",
      timeLabel: formatTime(record.checkOutTime),
      position: checkOutPosition,
      color: "#dc2626",
    });
  }

  return points;
}

function AttendanceMapViewport({ positions }: { positions: [number, number][] }) {
  const map = useMap();

  useEffect(() => {
    if (positions.length === 0) return;

    const timer = window.setTimeout(() => {
      if (positions.length === 1) {
        map.setView(positions[0], 16, { animate: false });
      } else {
        map.fitBounds(positions, { padding: [32, 32], maxZoom: 16 });
      }
      map.invalidateSize();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [map, positions]);

  return null;
}

function AttendanceLocationMap({ record }: { record: AttendanceRecord }) {
  const points = buildLocationPoints(record);

  if (points.length === 0) {
    return (
      <div className="h-72 rounded-2xl border border-dashed border-gray-200 bg-gray-50 flex flex-col items-center justify-center text-center px-6">
        <MapPin size={28} className="text-gray-300 mb-3" />
        <p className="text-sm font-medium text-gray-500">Lokasi absensi belum tersedia.</p>
        <p className="text-xs text-gray-400 mt-1">Data ini bisa kosong untuk absensi auto-generate atau yang belum check-out.</p>
      </div>
    );
  }

  return (
    <div className="h-72 rounded-2xl overflow-hidden border border-gray-200">
      <MapContainer center={points[0].position} zoom={16} className="h-full w-full z-0" scrollWheelZoom={false}>
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <AttendanceMapViewport positions={points.map((point) => point.position)} />
        {points.length > 1 && (
          <Polyline positions={points.map((point) => point.position)} pathOptions={{ color: "#94a3b8", weight: 3, opacity: 0.8, dashArray: "6 6" }} />
        )}
        {points.map((point) => (
          <CircleMarker
            key={point.key}
            center={point.position}
            radius={9}
            pathOptions={{
              color: point.color,
              fillColor: point.color,
              fillOpacity: 0.9,
              weight: 2,
            }}
          >
            <Popup>
              <div className="text-sm">
                <p className="font-semibold text-gray-900">{point.label}</p>
                <p className="text-gray-500">{point.timeLabel}</p>
                <p className="text-gray-500">
                  {formatCoordinate(point.position[0])}, {formatCoordinate(point.position[1])}
                </p>
              </div>
            </Popup>
          </CircleMarker>
        ))}
      </MapContainer>
    </div>
  );
}

export function AttendancePage() {
  const { toast, show: showToast } = useToast();
  const [records, setRecords] = useState<AttendanceRecord[]>([]);
  const [branches, setBranches] = useState<{ id: string; name: string }[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const debouncedSearch = useDebounce(searchTerm, 300);
  const [selectedBranch, setSelectedBranch] = useState("Semua Cabang");
  const [dateFilter, setDateFilter] = useState(() => new Date().toISOString().slice(0, 10));
  const [showFilterDropdown, setShowFilterDropdown] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalItems, setTotalItems] = useState(0);
  const itemsPerPage = 20;
  const [stats, setStats] = useState({ hadir: 0, terlambat: 0, izin: 0, alpha: 0 });
  const [statusFilter, setStatusFilter] = useState<string | null>(null);
  const branchesRef = useRef<{ id: string; name: string }[]>([]);
  const [showExportDialog, setShowExportDialog] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [showDetailModal, setShowDetailModal] = useState(false);
  const [selectedAttendance, setSelectedAttendance] = useState<AttendanceRecord | null>(null);

  const STATUS_FILTER_MAP: Record<string, string> = {
    HADIR: "HADIR",
    TERLAMBAT: "TERLAMBAT",
    IZIN: "IZIN",
    ALPHA: "ALPHA",
  };

  const buildFilterParams = useCallback(() => {
    const params: any = {};
    if (dateFilter) params["filter[date]"] = dateFilter;
    if (debouncedSearch) params.search = debouncedSearch;
    if (selectedBranch !== "Semua Cabang") {
      const branchObj = branchesRef.current.find((b) => b.name === selectedBranch);
      if (branchObj) params["filter[branchId]"] = branchObj.id;
    }
    if (statusFilter && STATUS_FILTER_MAP[statusFilter]) {
      params["filter[status]"] = STATUS_FILTER_MAP[statusFilter];
    }
    return params;
  }, [dateFilter, debouncedSearch, selectedBranch, statusFilter]);

  useEffect(() => {
    const fetchAttendances = async () => {
      setIsLoading(true);
      try {
        const params = {
          ...buildFilterParams(),
          "pagination[page]": currentPage,
          "pagination[limit]": itemsPerPage,
        };
        const res = await api.get("/attendances", { params });
        const data = res.data?.data ?? res.data;
        setRecords(Array.isArray(data) ? data : (data?.data ?? []));
        const pagination = res.data?.pagination;
        if (pagination) {
          setTotalPages(pagination.totalPages ?? 1);
          setTotalItems(pagination.totalItems ?? 0);
        }
        if (res.data?.stats) setStats(res.data.stats);
        if (res.data?.branches) {
          branchesRef.current = res.data.branches;
          setBranches(res.data.branches);
        }
      } finally {
        setIsLoading(false);
      }
    };
    fetchAttendances();
  }, [currentPage, buildFilterParams]);

  const handleExportExcel = async () => {
    setIsExporting(true);
    try {
      const res = await api.get("/attendances", {
        params: { ...buildFilterParams(), get_all: true },
      });
      const data = res.data?.data ?? res.data;
      const allRecords: AttendanceRecord[] = Array.isArray(data) ? data : (data?.data ?? []);

      const header = ["Tanggal", "Nama", "NIK", "Cabang", "Masuk", "Keluar", "Status", "Poin"];
      const rows = allRecords.map((r) => [
        formatDate(r.date),
        r.employee?.name ?? "-",
        r.employee?.nik ?? "-",
        r.employee?.branch?.name ?? r.branch?.name ?? "-",
        formatTime(r.checkInTime),
        formatTime(r.checkOutTime),
        STATUS_LABEL[r.status] ?? r.status,
        r.points,
      ]);

      const csvContent = [header, ...rows].map((row) => row.map((c) => `"${c}"`).join(",")).join("\n");
      const BOM = "\uFEFF";
      const blob = new Blob([BOM + csvContent], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `absensi-${dateFilter || "semua"}.csv`;
      a.click();
      URL.revokeObjectURL(url);

      setShowExportDialog(false);
      showToast(`Data berhasil diexport! (${allRecords.length} baris)`);
    } catch {
      showToast("Gagal mengambil data untuk export.", "error");
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportPDF = async () => {
    setIsExportingPdf(true);
    try {
      const res = await api.get("/attendances", {
        params: { ...buildFilterParams(), get_all: true },
      });
      const data = res.data?.data ?? res.data;
      const allRecords: AttendanceRecord[] = Array.isArray(data) ? data : (data?.data ?? []);

      const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

      const title = `Laporan Absensi — ${dateFilter ? new Date(dateFilter).toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" }) : "Semua Tanggal"}`;
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(title, 14, 16);

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120);
      doc.text(`Dicetak: ${new Date().toLocaleString("id-ID")}  |  Total: ${allRecords.length} data`, 14, 23);
      doc.setTextColor(0);

      autoTable(doc, {
        startY: 28,
        head: [["Tanggal", "Nama", "NIK", "Cabang", "Masuk", "Keluar", "Status", "Poin"]],
        body: allRecords.map((r) => [
          formatDate(r.date),
          r.employee?.name ?? "-",
          r.employee?.nik ?? "-",
          r.employee?.branch?.name ?? r.branch?.name ?? "-",
          formatTime(r.checkInTime),
          formatTime(r.checkOutTime),
          STATUS_LABEL[r.status] ?? r.status,
          r.points,
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        columnStyles: {
          0: { cellWidth: 28 },
          4: { halign: "center" },
          5: { halign: "center" },
          6: { halign: "center" },
          7: { halign: "center", cellWidth: 16 },
        },
      });

      doc.save(`absensi-${dateFilter || "semua"}.pdf`);
      setShowExportDialog(false);
      showToast(`PDF berhasil diunduh! (${allRecords.length} baris)`);
    } catch {
      showToast("Gagal generate PDF.", "error");
    } finally {
      setIsExportingPdf(false);
    }
  };

  const openDetailModal = (record: AttendanceRecord) => {
    setSelectedAttendance(record);
    setShowDetailModal(true);
  };

  const closeDetailModal = () => {
    setShowDetailModal(false);
    setSelectedAttendance(null);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-6"
    >
      <Toast toast={toast} />

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Total Hadir", value: stats.hadir, color: "text-emerald-600", bg: "bg-emerald-50", ring: "ring-emerald-400", filterKey: "HADIR" },
          { label: "Terlambat", value: stats.terlambat, color: "text-amber-600", bg: "bg-amber-50", ring: "ring-amber-400", filterKey: "TERLAMBAT" },
          { label: "Izin / Sakit", value: stats.izin, color: "text-blue-600", bg: "bg-blue-50", ring: "ring-blue-400", filterKey: "IZIN" },
          { label: "Alpha", value: stats.alpha, color: "text-red-600", bg: "bg-red-50", ring: "ring-red-400", filterKey: "ALPHA" },
        ].map((stat) => {
          const isActive = stat.filterKey && statusFilter === stat.filterKey;
          return (
            <button
              key={stat.label}
              onClick={() => {
                if (!stat.filterKey) return;
                setStatusFilter(isActive ? null : stat.filterKey);
                setCurrentPage(1);
              }}
              className={`bg-white p-4 rounded-xl border shadow-sm flex items-center justify-between w-full text-left transition-all duration-150 ${
                stat.filterKey ? "cursor-pointer hover:shadow-md" : "cursor-default"
              } ${isActive ? `ring-2 ${stat.ring} border-transparent` : "border-gray-100"}`}
            >
              <div className="flex flex-col gap-0.5">
                <span className="text-sm font-medium text-gray-500">{stat.label}</span>
                {isActive && <span className="text-[10px] text-gray-400">Klik untuk hapus filter</span>}
              </div>
              <span className={`text-xl font-bold px-3 py-1 rounded-lg ${stat.bg} ${stat.color}`}>
                {isLoading ? "..." : stat.value}
              </span>
            </button>
          );
        })}
      </div>

      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 bg-white p-4 rounded-xl shadow-sm border border-gray-100 relative z-20">
        <div className="flex flex-wrap items-center gap-3 w-full">
          <div className="relative flex-1 min-w-[140px]">
            <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
            <input
              type="date"
              value={dateFilter}
              onChange={(e) => { setDateFilter(e.target.value); setCurrentPage(1); }}
              className="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20"
            />
          </div>
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
            <input
              type="text"
              placeholder="Cari karyawan..."
              value={searchTerm}
              onChange={(e) => { setSearchTerm(e.target.value); setCurrentPage(1); }}
              className="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20"
            />
          </div>
          <div className="relative">
            <button
              onClick={() => setShowFilterDropdown(!showFilterDropdown)}
              className="flex items-center gap-2 px-3 py-2 bg-white border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 text-sm"
            >
              <Filter size={16} />
              <span>{selectedBranch === "Semua Cabang" ? "Filter" : selectedBranch}</span>
            </button>
            {showFilterDropdown && (
              <div className="absolute top-full mt-2 right-0 w-48 bg-white rounded-lg shadow-lg border border-gray-100 py-1 z-30">
                {["Semua Cabang", ...branches.map((b) => b.name)].map((branch) => (
                  <button
                    key={branch}
                    onClick={() => {
                      setSelectedBranch(branch);
                      setShowFilterDropdown(false);
                      setCurrentPage(1);
                    }}
                    className={`w-full text-left px-4 py-2 text-sm hover:bg-gray-50 ${selectedBranch === branch ? "text-blue-600 font-medium bg-blue-50" : "text-gray-700"}`}
                  >
                    {branch}
                  </button>
                ))}
              </div>
            )}
          </div>
          <button
            onClick={() => setShowExportDialog(true)}
            className="flex items-center gap-2 px-3 py-2 bg-emerald-50 text-emerald-600 border border-emerald-100 rounded-lg hover:bg-emerald-100 text-sm font-medium"
          >
            <Download size={16} />
            <span>Export</span>
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50/50 border-b border-gray-100 text-xs uppercase text-gray-500 font-semibold tracking-wider">
                <th className="px-6 py-4">Tanggal</th>
                <th className="px-6 py-4">Karyawan</th>
                <th className="px-6 py-4">Cabang</th>
                <th className="px-6 py-4 text-center">Masuk</th>
                <th className="px-6 py-4 text-center">Keluar</th>
                <th className="px-6 py-4 text-center">Status</th>
                <th className="px-6 py-4 text-center">Poin</th>
                <th className="px-6 py-4 text-center">Aksi</th>
              </tr>
            </thead>
            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan={8} className="px-6 py-10 text-center text-gray-400">
                    <Loader2 size={24} className="animate-spin mx-auto mb-2" />
                    Memuat data...
                  </td>
                </tr>
              ) : records.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-6 py-8 text-center text-gray-500">
                    Tidak ada data absensi ditemukan.
                  </td>
                </tr>
              ) : (
                records.map((record) => (
                  <tr key={record.id} className="hover:bg-gray-50/80 transition-colors border-b border-gray-50">
                    <td className="px-6 py-4 text-sm text-gray-500 whitespace-nowrap">{formatDate(record.date)}</td>
                    <td className="px-6 py-4">
                      <div>
                        <p className="text-sm font-medium text-gray-900">{record.employee?.name ?? "-"}</p>
                        <p className="text-xs text-gray-400">{record.employee?.nik ?? "-"}</p>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-500">{record.employee?.branch?.name ?? record.branch?.name ?? "-"}</td>
                    <td className="px-6 py-4 text-center text-sm font-mono text-gray-700">
                      {formatTime(record.checkInTime)}
                    </td>
                    <td className="px-6 py-4 text-center text-sm font-mono text-gray-700">
                      {formatTime(record.checkOutTime)}
                    </td>
                    <td className="px-6 py-4 text-center">
                      <span
                        className={`inline-flex px-2.5 py-1 rounded-full text-xs font-semibold border ${getStatusBadge(record.status)}`}
                      >
                        {STATUS_LABEL[record.status] ?? record.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <span
                        className={`inline-flex px-2.5 py-1 rounded-full text-xs font-bold ${record.points === 1 ? "bg-emerald-50 text-emerald-700" : record.points === 0.5 ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}
                      >
                        {record.points}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <button
                        onClick={() => openDetailModal(record)}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-50 text-blue-600 text-xs font-medium hover:bg-blue-100 transition-colors"
                      >
                        <Eye size={14} />
                        Detail
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          totalItems={totalItems}
          itemsPerPage={itemsPerPage}
          onPageChange={setCurrentPage}
          itemLabel="data"
        />
      </div>

      <AnimatePresence>
        {showDetailModal && selectedAttendance && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={closeDetailModal}
          >
            <motion.div
              initial={{ scale: 0.96, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.96, opacity: 0 }}
              className="bg-white rounded-2xl shadow-xl w-full max-w-6xl max-h-[90vh] overflow-hidden flex flex-col"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="px-6 py-5 border-b border-gray-100 flex items-start justify-between gap-4">
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="text-xl font-bold text-gray-900">Detail Absensi</h3>
                    <span className={`inline-flex px-2.5 py-1 rounded-full text-xs font-semibold border ${getStatusBadge(selectedAttendance.status)}`}>
                      {STATUS_LABEL[selectedAttendance.status] ?? selectedAttendance.status}
                    </span>
                    {selectedAttendance.isAutoGenerated && (
                      <span className="inline-flex px-2.5 py-1 rounded-full text-xs font-semibold border border-gray-200 bg-gray-50 text-gray-600">
                        Auto Generate
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-gray-600 mt-1">
                    {selectedAttendance.employee?.name ?? "-"} • {selectedAttendance.employee?.nik ?? "-"}
                  </p>
                  <p className="text-xs text-gray-400 mt-1">
                    {formatDate(selectedAttendance.date)} • {selectedAttendance.employee?.branch?.name ?? selectedAttendance.branch?.name ?? "-"}
                  </p>
                </div>
                <button
                  onClick={closeDetailModal}
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                  aria-label="Tutup detail absensi"
                >
                  <X size={20} />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-6 space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
                  <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
                    <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Jam Masuk</p>
                    <p className="text-xl font-bold text-gray-900 mt-2">{formatTime(selectedAttendance.checkInTime)}</p>
                  </div>
                  <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
                    <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Jam Keluar</p>
                    <p className="text-xl font-bold text-gray-900 mt-2">{formatTime(selectedAttendance.checkOutTime)}</p>
                  </div>
                  <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
                    <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Durasi Kerja</p>
                    <p className="text-xl font-bold text-gray-900 mt-2">{formatDuration(selectedAttendance.durationMinutes)}</p>
                  </div>
                  <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
                    <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Poin</p>
                    <p className="text-xl font-bold text-gray-900 mt-2">{selectedAttendance.points}</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 xl:grid-cols-[360px_minmax(0,1fr)] gap-6">
                  <div className="space-y-6">
                    <section className="rounded-2xl border border-gray-100 overflow-hidden bg-white">
                      <div className="px-4 py-3 border-b border-gray-100 flex items-center gap-2">
                        <Camera size={16} className="text-blue-500" />
                        <h4 className="font-semibold text-gray-900">Foto Absensi</h4>
                      </div>
                      {selectedAttendance.checkInPhoto ? (
                        <div className="p-4">
                          <img
                            src={getAssetUrl(selectedAttendance.checkInPhoto)}
                            alt={`Foto absensi ${selectedAttendance.employee?.name ?? ""}`}
                            className="w-full rounded-2xl object-cover max-h-[380px] bg-gray-100"
                          />
                        </div>
                      ) : (
                        <div className="px-6 py-10 text-center text-gray-400 bg-gray-50">
                          <Camera size={28} className="mx-auto mb-3 text-gray-300" />
                          <p className="text-sm font-medium">Foto absensi tidak tersedia.</p>
                        </div>
                      )}
                    </section>

                    <section className="rounded-2xl border border-gray-100 bg-white p-4 space-y-4">
                      <h4 className="font-semibold text-gray-900">Informasi Lokasi</h4>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <div className="rounded-xl border border-emerald-100 bg-emerald-50/70 p-3">
                          <p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Check-in</p>
                          <p className="text-sm text-gray-700 mt-2">Lat: {formatCoordinate(selectedAttendance.checkInLat)}</p>
                          <p className="text-sm text-gray-700">Lng: {formatCoordinate(selectedAttendance.checkInLng)}</p>
                        </div>
                        <div className="rounded-xl border border-rose-100 bg-rose-50/70 p-3">
                          <p className="text-xs font-semibold uppercase tracking-wide text-rose-700">Check-out</p>
                          <p className="text-sm text-gray-700 mt-2">Lat: {formatCoordinate(selectedAttendance.checkOutLat)}</p>
                          <p className="text-sm text-gray-700">Lng: {formatCoordinate(selectedAttendance.checkOutLng)}</p>
                        </div>
                      </div>
                      <div className="rounded-xl border border-gray-100 bg-gray-50 px-3 py-2 text-sm text-gray-600">
                        Status geofence check-in:{" "}
                        <span className="font-semibold text-gray-900">
                          {selectedAttendance.checkInLat == null || selectedAttendance.checkInLng == null
                            ? "Tidak ada data"
                            : selectedAttendance.checkInInsideRadius
                              ? "Di dalam radius"
                              : "Di luar radius"}
                        </span>
                      </div>
                    </section>
                  </div>

                  <section className="rounded-2xl border border-gray-100 overflow-hidden bg-white">
                    <div className="px-4 py-3 border-b border-gray-100 flex items-center gap-2">
                      <MapPin size={16} className="text-blue-500" />
                      <h4 className="font-semibold text-gray-900">Preview Lokasi</h4>
                    </div>
                    <div className="p-4 space-y-4">
                      <AttendanceLocationMap record={selectedAttendance} />
                      {buildLocationPoints(selectedAttendance).length > 0 && (
                        <div className="flex flex-wrap gap-2">
                          {buildLocationPoints(selectedAttendance).map((point) => (
                            <div key={point.key} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-gray-50 border border-gray-200 text-xs text-gray-600">
                              <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: point.color }} />
                              <span className="font-medium text-gray-700">{point.label}</span>
                              <span>{point.timeLabel}</span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </section>
                </div>
              </div>

              <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 flex justify-end">
                <button
                  onClick={closeDetailModal}
                  className="px-4 py-2 bg-white border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-100 font-medium text-sm"
                >
                  Tutup
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {showExportDialog && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white rounded-2xl shadow-xl w-full max-w-sm overflow-hidden"
            >
              <div className="p-6 text-center">
                <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Download size={24} />
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-2">Export Data Absensi</h3>
                <p className="text-gray-500 text-sm mb-6">Pilih format file untuk mengunduh data absensi.</p>
                <div className="grid grid-cols-2 gap-3">
                  <button
                    onClick={handleExportExcel}
                    disabled={isExporting}
                    className="flex flex-col items-center justify-center p-4 border border-gray-200 rounded-xl hover:bg-emerald-50 hover:border-emerald-200 hover:text-emerald-700 transition-all group disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isExporting ? (
                      <Loader2 size={24} className="mb-2 text-emerald-600 animate-spin" />
                    ) : (
                      <FileSpreadsheet size={24} className="mb-2 text-gray-400 group-hover:text-emerald-600" />
                    )}
                    <span className="text-sm font-medium">{isExporting ? "Memproses..." : "Excel (.csv)"}</span>
                  </button>
                  <button
                    onClick={handleExportPDF}
                    disabled={isExportingPdf}
                    className="flex flex-col items-center justify-center p-4 border border-gray-200 rounded-xl hover:bg-red-50 hover:border-red-200 hover:text-red-700 transition-all group disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isExportingPdf ? (
                      <Loader2 size={24} className="mb-2 text-red-600 animate-spin" />
                    ) : (
                      <FileText size={24} className="mb-2 text-gray-400 group-hover:text-red-600" />
                    )}
                    <span className="text-sm font-medium">{isExportingPdf ? "Memproses..." : "PDF (.pdf)"}</span>
                  </button>
                </div>
              </div>
              <div className="p-4 bg-gray-50 border-t border-gray-100 flex justify-center">
                <button
                  onClick={() => setShowExportDialog(false)}
                  className="text-gray-500 hover:text-gray-700 text-sm font-medium"
                >
                  Batal
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
